version: '3.9'

services:
  gateway-svc:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    links: 
    - user-svc
    - mongo
    ports:
    - 8000:8000
  user-svc:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports: 
      - 8001:8001
  mongo:
    image: mongo:4.2
    environment:
      MONGO_INITDB_DATABASE: MicroArch 
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: